import { Component, OnInit } from "@angular/core";

@Component({
  selector: "app-plans",
  templateUrl: "./plans.component.html",
  styleUrls: ["./plans.component.scss"],
})
export class PlansComponent {
  constructor() {}

  elements: any = [
    {
      select: "Essentials",
      free: "",
      basic: "",
      silver: "",
      gold: "",
      bg: "bg",
      icon: "d-none",
      xicon: "d-none",
    },
    {
      select: "Document",
      free: "",
      basic: "",
      silver: "",
      gold: "10000 Documents",
      icon: "d-none",
    },
    {
      select: "Smart Drive",
      free: "",
      basic: "",
      silver: "",
      gold: "10000 MB",
      icon: "d-none",
    },
    {
      select: "Customer and Supplier Management",
      free: "Ab",
      basic: "Ab",
      silver: "",
      gold: "",
      icon: "d-block",
    },
    {
      select: "Integrated Webmail",
      free: "",
      basic: "",
      silver: "",
      gold: "10000 MB",
      icon: "d-none",
    },
    {
      select: "Options page",
      free: "",
      basic: "",
      silver: "",
      gold: "",
      icon: "d-block",
    },
    {
      select: "Tax drawer",
      free: "",
      basic: "",
      silver: "",
      gold: "",
      icon: "d-block",
    },
    {
      select: "Main Features",
      free: "",
      basic: "",
      silver: "",
      gold: "",
      bg: "bg",
      icon: "d-none",
      xicon: "d-none",
    },
    {
      select: "Electronic Invoicing",
      free: "",
      basic: "",
      silver: "",
      gold: "10000 Documents",
      icon: "d-none",
    },
    {
      select: "Management of files, dossiers and files",
      free: "",
      basic: "",
      silver: "",
      gold: "10000 MB",
      icon: "d-none",
    },
    {
      select: "Advanced mailing's",
      free: "Ab",
      basic: "Ab",
      silver: "",
      gold: "",
      icon: "d-block",
    },
    {
      select: "TimeTable",
      free: "",
      basic: "",
      silver: "",
      gold: "10000 MB",
      icon: "d-none",
    },
    {
      select: "Print models",
      free: "",
      basic: "",
      silver: "",
      gold: "",
      icon: "d-block",
    },
    {
      select: "Payment method management",
      free: "",
      basic: "",
      silver: "",
      gold: "",
      icon: "d-block",
    },
    {
      select: "Invitees",
      free: "",
      basic: "",
      silver: "",
      gold: "",
      icon: "d-block",
    },
    {
      select: "Account and resource management",
      free: "",
      basic: "",
      silver: "",
      gold: "",
      icon: "d-block",
    },
    {
      select: "Agent",
      free: "",
      basic: "",
      silver: "",
      gold: "",
      icon: "d-block",
    },
    {
      select: "Product categories management",
      free: "",
      basic: "",
      silver: "",
      gold: "",
      icon: "d-block",
    },
    {
      select: "Support",
      free: "",
      basic: "",
      silver: "",
      gold: "",
      bg: "bg",
      icon: "d-none",
      xicon: "d-none",
    },

    {
      select: "Management of products and services",
      free: "",
      basic: "",
      silver: "",
      gold: "",
      icon: "d-block",
    },
    {
      select: "Rate management",
      free: "",
      basic: "",
      silver: "",
      gold: "",
      icon: "d-block",
    },
    {
      select: "Journal and payments",
      free: "",
      basic: "",
      silver: "",
      gold: "",
      icon: "d-block",
    },
    {
      select: "Notice Board",
      free: "",
      basic: "",
      silver: "",
      gold: "",
      icon: "d-block",
    },
    {
      select: "User Profile",
      free: "",
      basic: "",
      silver: "",
      gold: "",
      icon: "d-block",
    },
    {
      select: "Company profile",
      free: "",
      basic: "",
      silver: "",
      gold: "",
      icon: "d-block",
    },
    {
      select: "New document for professionals",
      free: "",
      basic: "",
      silver: "",
      gold: "",
      icon: "d-block",
    },
    {
      select: "Product_page_ean",
      free: "",
      basic: "",
      silver: "",
      gold: "",
      icon: "d-block",
    },
    {
      select: "Unit-measure",
      free: "",
      basic: "",
      silver: "",
      gold: "",
      icon: "d-block",
    },
    {
      select: "Email document management",
      free: "",
      basic: "",
      silver: "",
      gold: "",
      icon: "d-block",
    },
  ];
}
